
CBI="{{ grains['cbi_home'] }}"
export CBI

CBI_MACHINE="{{ grains['cbi_machine'] }}"
export CBI_MACHINE

ALTERNATE_EDITOR=""
export ALTERNATE_EDITOR

PATH=$PATH:$CBI/bin

{% if grains['cbi_machine'] in [ 'debussy', 'scriabin' ] %}
PATH=$PATH:/home/johannes/.gem/ruby/2.2.0/bin:/home/johannes/.gem/ruby/2.0.0/bin:/home/johannes/.cabal/bin:./.cabal-sandbox/bin

EDITOR="my_emacs -c -nw"
export EDITOR

{% endif %}

export PATH


if [ "$TERM" = "dumb" ]
then
       setopt no_global_rcs 
fi