#!/bin/bash

# converts a hex encoded number to a list of words

# the list:
# http://www1.ids-mannheim.de/kl/projekte/methoden/derewo.html
# http://www.ids-mannheim.de/kl/derewo/derewo-v-ww-bll-320000g-2012-12-31-1.0.zip
#converted to utf8-unix
# iconv -f latin1 -t utf8 | cut -f 1 -d\ |  sed -e 's/./\L\0/g' -e '/.*[(),#].*/d' | perl -nle '$l=length($_);print $l<6||$l>7 ? "" : $_ ' | sed -e 's/ö/oe/g' -e 's/ä/ae/g' -e 's/ü/ue/g' -e 's/ß/ss/g' -e '/^$/d' -e's/ //g' | sort -R

# 17292 words -> 2^14 = 16384

if [ "debug" = "$1" ]; then
		debug=1
		shift
fi

echo "VERIFY THE SIGNATURE OF THIS FILE!!!!!!!" 1>&2

echo 1dcb4d17d20338314a42f1913c91ba0f804795f13fc53b5f5e8d45640742b634065feac375e48dbcf86ca2e376ef018cfd8c4a6f21860c282306643056f9c9cf  Wortliste | sha512sum -c --strict 1>&2

if [ "$1" != "test" ]; then
		t=$(echo test123 | sha512sum | xxd -r -p | ./$0 test 2>/dev/null)
		if [ -n "$debug" ]; then echo -n "$t" 1>&2 ; fi 
		if [ "$t" != "leotard tanktop abteil softie whisky jaguar baaske liquet kumulus zusatz gedurft kelter alpinum gelocht mokant chemie lachen arznei timecop kullern henker rinnen bluter obenauf gehoert konvex access etwaig knille persil exarch umlage flappe jacuzzi bachab dealen tenakel tombola " ]; then
		echo TEST FAILED 1>&2
		fi
fi


declare -a words
readarray words < Wortliste

hx="`head | xxd -p | tr '[:lower:]' '[:upper:]'`"
if [ -n "$debug" ]; then echo $hx; fi
bi="$(echo "ibase=16;obase=2;$hx" | BC_LINE_LENGTH=16 bc | tr -d "\\" 2> /dev/null)"
if [ -n "$debug" ]; then echo $bi; fi
for b in $bi; do
		d=$(echo "obase=10;ibase=2;$b" | bc)
		if [ -n "$debug" ]; then echo $b $d; fi
		echo -n ${words[$d]}
		echo -n " "
		done







